import fs from 'fs';
import path from 'path';
import type { Finding } from './types.js';

export interface FixResult {
  file: string;
  action: 'created' | 'updated';
  descriptions: string[];
}

const MIGRATION_DIRS = [
  'supabase/migrations',
  'migrations',
  'db/migrations',
  'database/migrations',
];

export function applyFixes(
  root: string,
  findings: Finding[],
): { fixed: FixResult[]; unfixable: Finding[] } {
  const fixed: FixResult[] = [];
  const handledTitles = new Set<string>();

  // ── .gitignore fixes ─────────────────────────────────────────────────────
  const gitignoreNeeded = findings.filter(
    f => f.category === 'secrets' && f.title.includes('not in .gitignore'),
  );

  if (gitignoreNeeded.length > 0) {
    const gitignorePath = path.join(root, '.gitignore');
    let content = '';
    try { content = fs.readFileSync(gitignorePath, 'utf-8'); } catch { /* create it */ }

    const existing = new Set(content.split('\n').map(l => l.trim()));
    const toAdd = gitignoreNeeded
      .map(f => f.file!)
      .filter(Boolean)
      .filter(f => !existing.has(f) && !existing.has(`/${f}`) && !existing.has('.env*'));

    if (toAdd.length > 0) {
      const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
      fs.writeFileSync(gitignorePath, content + separator + '# Added by supafix\n' + toAdd.join('\n') + '\n');
      fixed.push({
        file: '.gitignore',
        action: 'updated',
        descriptions: toAdd.map(f => `Added "${f}"`),
      });
      for (const f of gitignoreNeeded) handledTitles.add(f.title);
    }
  }

  // ── RLS migration ─────────────────────────────────────────────────────────
  const noRlsFindings = findings.filter(
    f => f.category === 'rls' && f.title.includes('no Row Level Security'),
  );
  const noPolicyFindings = findings.filter(
    f => f.category === 'rls' && f.title.includes('no policies'),
  );

  if (noRlsFindings.length > 0 || noPolicyFindings.length > 0) {
    const migDir = findOrCreateMigDir(root);
    const timestamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
    const descriptions: string[] = [];

    let sql = '-- Generated by supafix\n';
    sql += `-- ${new Date().toUTCString()}\n`;
    sql += '-- IMPORTANT: Review every statement below before applying to production.\n\n';

    for (const f of noRlsFindings) {
      const tableMatch = f.title.match(/"([^"]+)"/);
      if (!tableMatch) continue;
      const table = tableMatch[1];
      sql += `ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;\n\n`;
      descriptions.push(`Enable RLS on "${table}"`);
      handledTitles.add(f.title);
    }

    for (const f of noPolicyFindings) {
      const tableMatch = f.title.match(/"([^"]+)"/);
      if (!tableMatch) continue;
      const table = tableMatch[1];
      sql += `-- Stub policy for "${table}" — replace USING / WITH CHECK with your actual rules\n`;
      sql += `CREATE POLICY "authenticated_access" ON ${table}\n`;
      sql += `  FOR ALL\n`;
      sql += `  USING (auth.uid() IS NOT NULL)\n`;
      sql += `  WITH CHECK (auth.uid() IS NOT NULL);\n\n`;
      descriptions.push(`Stub policy for "${table}" (needs customisation)`);
      handledTitles.add(f.title);
    }

    const fixFile = path.join(migDir, `${timestamp}_supabase_guard_fixes.sql`);
    fs.writeFileSync(fixFile, sql);
    fixed.push({
      file: path.relative(root, fixFile),
      action: 'created',
      descriptions,
    });
  }

  const unfixable = findings.filter(f => !handledTitles.has(f.title));
  return { fixed, unfixable };
}

export function printFixReport(
  fixed: FixResult[],
  unfixable: Finding[],
  writer: (s: string) => void = s => process.stdout.write(s),
): void {
  const NO_COLOR = !!process.env.NO_COLOR || process.env.TERM === 'dumb';
  const green = (s: string) => NO_COLOR ? s : `\x1b[32m${s}\x1b[0m`;
  const dim   = (s: string) => NO_COLOR ? s : `\x1b[2m${s}\x1b[0m`;
  const bold  = (s: string) => NO_COLOR ? s : `\x1b[1m${s}\x1b[0m`;
  const yellow = (s: string) => NO_COLOR ? s : `\x1b[33m${s}\x1b[0m`;

  writer('\n');

  if (fixed.length === 0 && unfixable.length === 0) {
    writer(green('  ✔  Nothing to fix.\n'));
    writer('\n');
    return;
  }

  if (fixed.length > 0) {
    writer(bold('  Auto-fixed\n'));
    writer(dim('  ─────────────────────────────────────────────\n'));
    for (const r of fixed) {
      writer(`\n  ${green('✔')}  ${r.action === 'created' ? 'Created' : 'Updated'} ${r.file}\n`);
      for (const d of r.descriptions) {
        writer(`     ${dim('·')} ${d}\n`);
      }
    }
    writer('\n');
  }

  if (unfixable.length > 0) {
    const unfixableCount = unfixable.length;
    writer(bold(`  Needs manual attention  ${dim(`(${unfixableCount} issue${unfixableCount > 1 ? 's' : ''})`)}\n`));
    writer(dim('  ─────────────────────────────────────────────\n'));
    for (const f of unfixable) {
      const icon = f.severity === 'critical' ? '✖' : f.severity === 'warning' ? '⚠' : '·';
      writer(`  ${icon}  ${f.title}\n`);
      if (f.file) writer(`     ${dim('→')} ${f.file}${f.line ? `:${f.line}` : ''}\n`);
    }
    writer('\n');
  }

  if (fixed.length > 0) {
    writer(dim('  Run ') + 'npx supafix' + dim(' to verify.\n'));
    writer('\n');
  }

  if (fixed.some(r => r.file.endsWith('.sql'))) {
    writer(yellow('  ⚠  Review the generated migration before running supabase db push.\n'));
    writer('\n');
  }
}

function findOrCreateMigDir(root: string): string {
  for (const d of MIGRATION_DIRS) {
    const full = path.join(root, d);
    try {
      if (fs.statSync(full).isDirectory()) return full;
    } catch { /* not found */ }
  }
  const fallback = path.join(root, 'supabase/migrations');
  fs.mkdirSync(fallback, { recursive: true });
  return fallback;
}
